#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/targetctl targetctl /usr/bin/targetctl-python3 200
	# If file doesn't exist or is of size zero, write it...
	if [ ! -s /etc/rtslib-fb-target/saveconfig.json ] ; then
		echo "{
  \"fabric_modules\": [],
  \"storage_objects\": [],
  \"targets\": []
}" >/etc/rtslib-fb-target/saveconfig.json
	fi
fi

#DEBHELPER#
